### ISSUE TITLE
New Endpoints

### ISSUE THREAD

**Issue by torbenkeller** [kevinskyba/kickbase-api-doc#2] opened 2024-02-18 14:43 UTC
I've discovered some new endpoints. Especially the new competition endpoints are helpful to get data about other competitions than Bundesliga.

The competitionId is incremental and starts by 1.
1: Bundesliga
2: 2. Bundesliga
3: La Liga
4: Google Gixel Frauen Bundesliga

The authorization also changed. Now you have to set the Authorization Header to Bearer {token}

```
/v3/leagues/{leagueId}/table?matchDay=22
/v3/leagues/{leagueId}/scoutedplayers
/v3/leagues/{leagueId}/overview
/v3/competitions/{competitionId}/table
/v3/competitions/{competitionId}/players?sorting=1&position=0
/v3/competitions/{competitionId}/overview
/v3/competitions/{competitionId}/matches?matchDay=22
/v2/notifications?leagueId={leagueId}
/v2/leagues/selection
/v2/leagues/{leagueId}/stats
/v2/leagues/{leagueId}/manager/squad
/v2/leagues/{leagueId}/livetable
/v2/leagues/{leagueId}/feed?filter=1,3,5,13,15,16,17,18,20,21&start=30
/v2/leagues/{leagueId}/feed?filter=1,3,5,13,15,16,17,18,20,21&start=0
/v2/leagues/{leagueId}/basecards
/user/targets
/user/settings
/user/login
/players/{playerId}/points
/live/top10?competitionId=2
/leagues/{leagueId}/users/{userId}/stats
/leagues/{leagueId}/users/{userId}/profile
/leagues/{leagueId}/users/{userId}/players
/leagues/{leagueId}/users/{userId}/lineup
/leagues/{leagueId}/users/{userId}/feed?filter=12%2C2&start=50
/leagues/{leagueId}/users/{userId}/feed?filter=12%2C2&start=25
/leagues/{leagueId}/users/{userId}/feed?filter=12%2C2&start=0
/leagues/{leagueId}/users/{userId}/feed?filter=11&start=0
/leagues/{leagueId}/stats
/leagues/{leagueId}/players/{playerId}/stats
/leagues/{leagueId}/players/{playerId}/feed?filter=14&start=0
/leagues/{leagueId}/players/{playerId}
/leagues/{leagueId}/me
/leagues/{leagueId}/market
/leagues/{leagueId}/live/players/{playerId}
/leagues/{leagueId}/live/linedupplayers
/leagues/{leagueId}/live
/leagues/{leagueId}/currentgift
/competition/search?query={name}
/
```

**Comment by FlexcelB** [comment] 2024-07-24 09:44
I'm still struggling on getting the list of transfers of a single user. am I missing an endpoint for this?

**Comment by torbenkeller** [comment] 2024-07-24 09:47
There may be more endpoints. Especially after the new version of kickbase

**Comment by kevinskyba** [comment] 2024-07-24 09:54
@torbenkeller do you mind adding these endpoints to the api and creating a pull request?

**Comment by phenze** [comment] 2024-07-24 16:02
Have anybody an idea how to get the token for authorization when the login in the app was via appleid or facebook login?

in the old version of the app there was the opportunity to set a custom password but i cannot find it in the new version

**Comment by ludw1** [comment] 2024-08-05 09:20
> Have anybody an idea how to get the token for authorization when the login in the app was via appleid or facebook login?
> 
> in the old version of the app there was the opportunity to set a custom password but i cannot find it in the new version

If you still have this issue, I think you can write to the support and they will handle this for you.

**Comment by Cray5701** [comment] 2024-10-25 09:19
Did anybody find the endpoint for selling a player to kickbase since the big update?

**Comment by Cray5701** [comment] 2024-10-25 10:25
Yeah you can make an offer to the Market but you cannot accept the offer made by kickbase

**Comment by Kradepon** [comment] 2024-11-07 01:59
> /user/login

Seems not to work anymore. I receive an HTTP 404 when i POST to this URL.

**Comment by casudo** [comment] 2024-11-07 05:47
> > /user/login
> 
> 
> 
> Seems not to work anymore. I receive an HTTP 404 when i POST to this URL.

I can confirm that.

**Comment by casudo** [comment] 2024-11-07 07:41
@torbenkeller @kevinskyba Kickbase has depricated all legacy, v2 and v3 API endpoints.

The new endpoints are used in v4.

I would recommend closing this issue to not cause confusions. I am currently in the process of collecting all new endpoints.

**Comment by Cray5701** [comment] 2024-11-07 07:47
I already collected them via Wireshark!

**Closed** 2024-11-07 08:40 UTC

**Comment by simonsagstetter** [comment] 2024-11-08 11:06
This is really sad.... I just finished a alternative webclient for viewing stats which I was going to post in a few weeks. I needed to use a lot of the old legacy, v2 and v3 endpoints to get the correct data. I struggled finding good v4 endpoints with similar data structures. I dont think I have time to fix this, so Im gonna share with you what I found during the development.

Those are the ones I found:
/v4/user/login Login
/v4/leagues/<leagueId>/overview League Stats
/v4/leagues/<leagueId>/squad Your own squad
/v4/leagues/<leagueId>/managers/<userId>/squad Squad Info
/v4/leagues/<leagueId>/ranking League Ranking
/v4/leagues/<leagueId>/players/<playerId> Player Info via league Id
/v4/competitions/<competitionId>/matchdays Fixtures
/v4/competitions/<competitionId>/table Leaderboard
/v4/competitions/<competitionId>/players Top 25 Players
/v4/competitions/<competitionId>/players/<playerId> Player Info via competition Id
